using Xunit;

namespace SystemIntelligencePlatform.EntityFrameworkCore;

[CollectionDefinition(SystemIntelligencePlatformTestConsts.CollectionDefinitionName)]
public class SystemIntelligencePlatformEntityFrameworkCoreCollection : ICollectionFixture<SystemIntelligencePlatformEntityFrameworkCoreFixture>
{

}
