using Volo.Abp;

namespace SystemIntelligencePlatform.EntityFrameworkCore;

public abstract class SystemIntelligencePlatformEntityFrameworkCoreTestBase : SystemIntelligencePlatformTestBase<SystemIntelligencePlatformEntityFrameworkCoreTestModule>
{

}
