using SystemIntelligencePlatform.EntityFrameworkCore;
using Xunit;

namespace SystemIntelligencePlatform.EntityFrameworkCore;

public class SystemIntelligencePlatformEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SystemIntelligencePlatformEntityFrameworkCoreFixture>
{

}
